### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ssuki27** [scivision/python-grwave#1]
Hi!

I had tried to execute your code but I have a error related to "subprocess.py" of Anaconda. "The system cannot find the file specified" (when subprocess.py call "startupinfo", I think).

What distribution of Python you use? Maybe my problem is because of this. I add a screenshot.

Thanks.

![Error anaconda](https://user-images.githubusercontent.com/60971859/75442594-20c90980-5960-11ea-89c6-d44802a8d3d2.jpg)

**Comment by scivision** [comment]
Thank you, the package was modernized and this issue was fixed.
